[package]
name = "delaunay"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
path = "src/libdelaunay.rs"

[dependencies]
cxx = "1.0.9"
# nalgebra = "0.33.1"
overload = "0.1.1"
rand = "0.9.0-alpha.2"
anyhow = "1.0.91"
[build-dependencies]
cxx-build = "1.0.129"
